info:
  version: @project.version@
  stage: dev

server:
  port: @server.port@

management:
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
  security:
    flag: false
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: @project.name@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 3
  flyway:
    table: schema_version
    schemas: @db.schema@
  output:
    ansi:
      enabled: always

fistful:
  polling:
    enabled: false

wallet:
  polling:
    url: http://localhost:8022/v1/eventsink/wallet
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    querySize: 100

withdrawal:
  polling:
    url: http://localhost:8022/v1/eventsink/withdrawal
    delay: 10000
    retryDelay: 1000
    maxPoolSize: 1
    querySize: 100

kafka:
  bootstrap-servers: changeit:9092
  consumer:
    group-id: scrooge
    concurrency: 7
  max-poll-records: 100
  max-poll-interval-ms: 60000
  max-session-timeout-ms: 60000
  ssl:
    enabled: false
    key-store-type: changeit
    key-store-location: changeit
    key-password: changeit
    trust-store-type: changeit
    trust-store-location: changeit
    trust-store-password: changeit
  topic:
    deposit:
      name: mg-events-ff-deposit
      listener:
        enabled: false
    identity:
      name: mg-events-ff-identity
      listener:
        enabled: false
    wallet:
      name: mg-events-ff-wallet
      listener:
        enabled: false
    withdrawal:
      name: mg-events-ff-withdrawal
      listener:
        enabled: false
