/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.pojos;


import com.rbkmoney.fistful.magista.domain.enums.ChallengeEventType;
import com.rbkmoney.fistful.magista.domain.enums.ChallengeResolution;
import com.rbkmoney.fistful.magista.domain.enums.ChallengeStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChallengeEvent implements Serializable {

    private static final long serialVersionUID = -2022279476;

    private Long                id;
    private Long                eventId;
    private ChallengeEventType  eventType;
    private LocalDateTime       eventCreatedAt;
    private LocalDateTime       eventOccuredAt;
    private Integer             sequenceId;
    private LocalDateTime       occuredAt;
    private String              identityId;
    private String              challengeId;
    private ChallengeStatus     challengeStatus;
    private ChallengeResolution challengeResolution;
    private LocalDateTime       challengeValidUntil;

    public ChallengeEvent() {}

    public ChallengeEvent(ChallengeEvent value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.eventType = value.eventType;
        this.eventCreatedAt = value.eventCreatedAt;
        this.eventOccuredAt = value.eventOccuredAt;
        this.sequenceId = value.sequenceId;
        this.occuredAt = value.occuredAt;
        this.identityId = value.identityId;
        this.challengeId = value.challengeId;
        this.challengeStatus = value.challengeStatus;
        this.challengeResolution = value.challengeResolution;
        this.challengeValidUntil = value.challengeValidUntil;
    }

    public ChallengeEvent(
        Long                id,
        Long                eventId,
        ChallengeEventType  eventType,
        LocalDateTime       eventCreatedAt,
        LocalDateTime       eventOccuredAt,
        Integer             sequenceId,
        LocalDateTime       occuredAt,
        String              identityId,
        String              challengeId,
        ChallengeStatus     challengeStatus,
        ChallengeResolution challengeResolution,
        LocalDateTime       challengeValidUntil
    ) {
        this.id = id;
        this.eventId = eventId;
        this.eventType = eventType;
        this.eventCreatedAt = eventCreatedAt;
        this.eventOccuredAt = eventOccuredAt;
        this.sequenceId = sequenceId;
        this.occuredAt = occuredAt;
        this.identityId = identityId;
        this.challengeId = challengeId;
        this.challengeStatus = challengeStatus;
        this.challengeResolution = challengeResolution;
        this.challengeValidUntil = challengeValidUntil;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventId() {
        return this.eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public ChallengeEventType getEventType() {
        return this.eventType;
    }

    public void setEventType(ChallengeEventType eventType) {
        this.eventType = eventType;
    }

    public LocalDateTime getEventCreatedAt() {
        return this.eventCreatedAt;
    }

    public void setEventCreatedAt(LocalDateTime eventCreatedAt) {
        this.eventCreatedAt = eventCreatedAt;
    }

    public LocalDateTime getEventOccuredAt() {
        return this.eventOccuredAt;
    }

    public void setEventOccuredAt(LocalDateTime eventOccuredAt) {
        this.eventOccuredAt = eventOccuredAt;
    }

    public Integer getSequenceId() {
        return this.sequenceId;
    }

    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    public LocalDateTime getOccuredAt() {
        return this.occuredAt;
    }

    public void setOccuredAt(LocalDateTime occuredAt) {
        this.occuredAt = occuredAt;
    }

    public String getIdentityId() {
        return this.identityId;
    }

    public void setIdentityId(String identityId) {
        this.identityId = identityId;
    }

    public String getChallengeId() {
        return this.challengeId;
    }

    public void setChallengeId(String challengeId) {
        this.challengeId = challengeId;
    }

    public ChallengeStatus getChallengeStatus() {
        return this.challengeStatus;
    }

    public void setChallengeStatus(ChallengeStatus challengeStatus) {
        this.challengeStatus = challengeStatus;
    }

    public ChallengeResolution getChallengeResolution() {
        return this.challengeResolution;
    }

    public void setChallengeResolution(ChallengeResolution challengeResolution) {
        this.challengeResolution = challengeResolution;
    }

    public LocalDateTime getChallengeValidUntil() {
        return this.challengeValidUntil;
    }

    public void setChallengeValidUntil(LocalDateTime challengeValidUntil) {
        this.challengeValidUntil = challengeValidUntil;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChallengeEvent other = (ChallengeEvent) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!eventId.equals(other.eventId))
            return false;
        if (eventType == null) {
            if (other.eventType != null)
                return false;
        }
        else if (!eventType.equals(other.eventType))
            return false;
        if (eventCreatedAt == null) {
            if (other.eventCreatedAt != null)
                return false;
        }
        else if (!eventCreatedAt.equals(other.eventCreatedAt))
            return false;
        if (eventOccuredAt == null) {
            if (other.eventOccuredAt != null)
                return false;
        }
        else if (!eventOccuredAt.equals(other.eventOccuredAt))
            return false;
        if (sequenceId == null) {
            if (other.sequenceId != null)
                return false;
        }
        else if (!sequenceId.equals(other.sequenceId))
            return false;
        if (occuredAt == null) {
            if (other.occuredAt != null)
                return false;
        }
        else if (!occuredAt.equals(other.occuredAt))
            return false;
        if (identityId == null) {
            if (other.identityId != null)
                return false;
        }
        else if (!identityId.equals(other.identityId))
            return false;
        if (challengeId == null) {
            if (other.challengeId != null)
                return false;
        }
        else if (!challengeId.equals(other.challengeId))
            return false;
        if (challengeStatus == null) {
            if (other.challengeStatus != null)
                return false;
        }
        else if (!challengeStatus.equals(other.challengeStatus))
            return false;
        if (challengeResolution == null) {
            if (other.challengeResolution != null)
                return false;
        }
        else if (!challengeResolution.equals(other.challengeResolution))
            return false;
        if (challengeValidUntil == null) {
            if (other.challengeValidUntil != null)
                return false;
        }
        else if (!challengeValidUntil.equals(other.challengeValidUntil))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.eventType == null) ? 0 : this.eventType.hashCode());
        result = prime * result + ((this.eventCreatedAt == null) ? 0 : this.eventCreatedAt.hashCode());
        result = prime * result + ((this.eventOccuredAt == null) ? 0 : this.eventOccuredAt.hashCode());
        result = prime * result + ((this.sequenceId == null) ? 0 : this.sequenceId.hashCode());
        result = prime * result + ((this.occuredAt == null) ? 0 : this.occuredAt.hashCode());
        result = prime * result + ((this.identityId == null) ? 0 : this.identityId.hashCode());
        result = prime * result + ((this.challengeId == null) ? 0 : this.challengeId.hashCode());
        result = prime * result + ((this.challengeStatus == null) ? 0 : this.challengeStatus.hashCode());
        result = prime * result + ((this.challengeResolution == null) ? 0 : this.challengeResolution.hashCode());
        result = prime * result + ((this.challengeValidUntil == null) ? 0 : this.challengeValidUntil.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChallengeEvent (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(eventType);
        sb.append(", ").append(eventCreatedAt);
        sb.append(", ").append(eventOccuredAt);
        sb.append(", ").append(sequenceId);
        sb.append(", ").append(occuredAt);
        sb.append(", ").append(identityId);
        sb.append(", ").append(challengeId);
        sb.append(", ").append(challengeStatus);
        sb.append(", ").append(challengeResolution);
        sb.append(", ").append(challengeValidUntil);

        sb.append(")");
        return sb.toString();
    }
}
