/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ChallengeData implements Serializable {

    private static final long serialVersionUID = 1533274476;

    private Long id;
    private String identityId;
    private String challengeId;
    private String challengeClassId;

    public ChallengeData() {
    }

    public ChallengeData(ChallengeData value) {
        this.id = value.id;
        this.identityId = value.identityId;
        this.challengeId = value.challengeId;
        this.challengeClassId = value.challengeClassId;
    }

    public ChallengeData(
            Long id,
            String identityId,
            String challengeId,
            String challengeClassId
    ) {
        this.id = id;
        this.identityId = identityId;
        this.challengeId = challengeId;
        this.challengeClassId = challengeClassId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentityId() {
        return this.identityId;
    }

    public void setIdentityId(String identityId) {
        this.identityId = identityId;
    }

    public String getChallengeId() {
        return this.challengeId;
    }

    public void setChallengeId(String challengeId) {
        this.challengeId = challengeId;
    }

    public String getChallengeClassId() {
        return this.challengeClassId;
    }

    public void setChallengeClassId(String challengeClassId) {
        this.challengeClassId = challengeClassId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChallengeData other = (ChallengeData) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (identityId == null) {
            if (other.identityId != null)
                return false;
        } else if (!identityId.equals(other.identityId))
            return false;
        if (challengeId == null) {
            if (other.challengeId != null)
                return false;
        } else if (!challengeId.equals(other.challengeId))
            return false;
        if (challengeClassId == null) {
            if (other.challengeClassId != null)
                return false;
        } else if (!challengeClassId.equals(other.challengeClassId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.identityId == null) ? 0 : this.identityId.hashCode());
        result = prime * result + ((this.challengeId == null) ? 0 : this.challengeId.hashCode());
        result = prime * result + ((this.challengeClassId == null) ? 0 : this.challengeClassId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChallengeData (");

        sb.append(id);
        sb.append(", ").append(identityId);
        sb.append(", ").append(challengeId);
        sb.append(", ").append(challengeClassId);

        sb.append(")");
        return sb.toString();
    }
}
