/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdentityData implements Serializable {

    private static final long serialVersionUID = 1185652950;

    private Long   id;
    private UUID   partyId;
    private String partyContractId;
    private String identityId;
    private String identityProviderId;
    private String identityClassId;

    public IdentityData() {}

    public IdentityData(IdentityData value) {
        this.id = value.id;
        this.partyId = value.partyId;
        this.partyContractId = value.partyContractId;
        this.identityId = value.identityId;
        this.identityProviderId = value.identityProviderId;
        this.identityClassId = value.identityClassId;
    }

    public IdentityData(
        Long   id,
        UUID   partyId,
        String partyContractId,
        String identityId,
        String identityProviderId,
        String identityClassId
    ) {
        this.id = id;
        this.partyId = partyId;
        this.partyContractId = partyContractId;
        this.identityId = identityId;
        this.identityProviderId = identityProviderId;
        this.identityClassId = identityClassId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UUID getPartyId() {
        return this.partyId;
    }

    public void setPartyId(UUID partyId) {
        this.partyId = partyId;
    }

    public String getPartyContractId() {
        return this.partyContractId;
    }

    public void setPartyContractId(String partyContractId) {
        this.partyContractId = partyContractId;
    }

    public String getIdentityId() {
        return this.identityId;
    }

    public void setIdentityId(String identityId) {
        this.identityId = identityId;
    }

    public String getIdentityProviderId() {
        return this.identityProviderId;
    }

    public void setIdentityProviderId(String identityProviderId) {
        this.identityProviderId = identityProviderId;
    }

    public String getIdentityClassId() {
        return this.identityClassId;
    }

    public void setIdentityClassId(String identityClassId) {
        this.identityClassId = identityClassId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IdentityData other = (IdentityData) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (partyContractId == null) {
            if (other.partyContractId != null)
                return false;
        }
        else if (!partyContractId.equals(other.partyContractId))
            return false;
        if (identityId == null) {
            if (other.identityId != null)
                return false;
        }
        else if (!identityId.equals(other.identityId))
            return false;
        if (identityProviderId == null) {
            if (other.identityProviderId != null)
                return false;
        }
        else if (!identityProviderId.equals(other.identityProviderId))
            return false;
        if (identityClassId == null) {
            if (other.identityClassId != null)
                return false;
        }
        else if (!identityClassId.equals(other.identityClassId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.partyContractId == null) ? 0 : this.partyContractId.hashCode());
        result = prime * result + ((this.identityId == null) ? 0 : this.identityId.hashCode());
        result = prime * result + ((this.identityProviderId == null) ? 0 : this.identityProviderId.hashCode());
        result = prime * result + ((this.identityClassId == null) ? 0 : this.identityClassId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IdentityData (");

        sb.append(id);
        sb.append(", ").append(partyId);
        sb.append(", ").append(partyContractId);
        sb.append(", ").append(identityId);
        sb.append(", ").append(identityProviderId);
        sb.append(", ").append(identityClassId);

        sb.append(")");
        return sb.toString();
    }
}
