/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WalletData implements Serializable {

    private static final long serialVersionUID = 91362373;

    private Long id;
    private String walletId;
    private String walletName;

    public WalletData() {
    }

    public WalletData(WalletData value) {
        this.id = value.id;
        this.walletId = value.walletId;
        this.walletName = value.walletName;
    }

    public WalletData(
            Long id,
            String walletId,
            String walletName
    ) {
        this.id = id;
        this.walletId = walletId;
        this.walletName = walletName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWalletId() {
        return this.walletId;
    }

    public void setWalletId(String walletId) {
        this.walletId = walletId;
    }

    public String getWalletName() {
        return this.walletName;
    }

    public void setWalletName(String walletName) {
        this.walletName = walletName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WalletData other = (WalletData) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (walletId == null) {
            if (other.walletId != null)
                return false;
        } else if (!walletId.equals(other.walletId))
            return false;
        if (walletName == null) {
            if (other.walletName != null)
                return false;
        } else if (!walletName.equals(other.walletName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.walletId == null) ? 0 : this.walletId.hashCode());
        result = prime * result + ((this.walletName == null) ? 0 : this.walletName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WalletData (");

        sb.append(id);
        sb.append(", ").append(walletId);
        sb.append(", ").append(walletName);

        sb.append(")");
        return sb.toString();
    }
}
