/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.pojos;


import com.rbkmoney.fistful.magista.domain.enums.WalletEventType;

import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WalletEvent implements Serializable {

    private static final long serialVersionUID = 794760403;

    private Long id;
    private Long eventId;
    private WalletEventType eventType;
    private LocalDateTime eventCreatedAt;
    private LocalDateTime eventOccuredAt;
    private Integer sequenceId;
    private LocalDateTime occuredAt;
    private String walletId;
    private String identityId;
    private String currencyCode;

    public WalletEvent() {
    }

    public WalletEvent(WalletEvent value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.eventType = value.eventType;
        this.eventCreatedAt = value.eventCreatedAt;
        this.eventOccuredAt = value.eventOccuredAt;
        this.sequenceId = value.sequenceId;
        this.occuredAt = value.occuredAt;
        this.walletId = value.walletId;
        this.identityId = value.identityId;
        this.currencyCode = value.currencyCode;
    }

    public WalletEvent(
            Long id,
            Long eventId,
            WalletEventType eventType,
            LocalDateTime eventCreatedAt,
            LocalDateTime eventOccuredAt,
            Integer sequenceId,
            LocalDateTime occuredAt,
            String walletId,
            String identityId,
            String currencyCode
    ) {
        this.id = id;
        this.eventId = eventId;
        this.eventType = eventType;
        this.eventCreatedAt = eventCreatedAt;
        this.eventOccuredAt = eventOccuredAt;
        this.sequenceId = sequenceId;
        this.occuredAt = occuredAt;
        this.walletId = walletId;
        this.identityId = identityId;
        this.currencyCode = currencyCode;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventId() {
        return this.eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public WalletEventType getEventType() {
        return this.eventType;
    }

    public void setEventType(WalletEventType eventType) {
        this.eventType = eventType;
    }

    public LocalDateTime getEventCreatedAt() {
        return this.eventCreatedAt;
    }

    public void setEventCreatedAt(LocalDateTime eventCreatedAt) {
        this.eventCreatedAt = eventCreatedAt;
    }

    public LocalDateTime getEventOccuredAt() {
        return this.eventOccuredAt;
    }

    public void setEventOccuredAt(LocalDateTime eventOccuredAt) {
        this.eventOccuredAt = eventOccuredAt;
    }

    public Integer getSequenceId() {
        return this.sequenceId;
    }

    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    public LocalDateTime getOccuredAt() {
        return this.occuredAt;
    }

    public void setOccuredAt(LocalDateTime occuredAt) {
        this.occuredAt = occuredAt;
    }

    public String getWalletId() {
        return this.walletId;
    }

    public void setWalletId(String walletId) {
        this.walletId = walletId;
    }

    public String getIdentityId() {
        return this.identityId;
    }

    public void setIdentityId(String identityId) {
        this.identityId = identityId;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WalletEvent other = (WalletEvent) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        } else if (!eventId.equals(other.eventId))
            return false;
        if (eventType == null) {
            if (other.eventType != null)
                return false;
        } else if (!eventType.equals(other.eventType))
            return false;
        if (eventCreatedAt == null) {
            if (other.eventCreatedAt != null)
                return false;
        } else if (!eventCreatedAt.equals(other.eventCreatedAt))
            return false;
        if (eventOccuredAt == null) {
            if (other.eventOccuredAt != null)
                return false;
        } else if (!eventOccuredAt.equals(other.eventOccuredAt))
            return false;
        if (sequenceId == null) {
            if (other.sequenceId != null)
                return false;
        } else if (!sequenceId.equals(other.sequenceId))
            return false;
        if (occuredAt == null) {
            if (other.occuredAt != null)
                return false;
        } else if (!occuredAt.equals(other.occuredAt))
            return false;
        if (walletId == null) {
            if (other.walletId != null)
                return false;
        } else if (!walletId.equals(other.walletId))
            return false;
        if (identityId == null) {
            if (other.identityId != null)
                return false;
        } else if (!identityId.equals(other.identityId))
            return false;
        if (currencyCode == null) {
            if (other.currencyCode != null)
                return false;
        } else if (!currencyCode.equals(other.currencyCode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.eventType == null) ? 0 : this.eventType.hashCode());
        result = prime * result + ((this.eventCreatedAt == null) ? 0 : this.eventCreatedAt.hashCode());
        result = prime * result + ((this.eventOccuredAt == null) ? 0 : this.eventOccuredAt.hashCode());
        result = prime * result + ((this.sequenceId == null) ? 0 : this.sequenceId.hashCode());
        result = prime * result + ((this.occuredAt == null) ? 0 : this.occuredAt.hashCode());
        result = prime * result + ((this.walletId == null) ? 0 : this.walletId.hashCode());
        result = prime * result + ((this.identityId == null) ? 0 : this.identityId.hashCode());
        result = prime * result + ((this.currencyCode == null) ? 0 : this.currencyCode.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WalletEvent (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(eventType);
        sb.append(", ").append(eventCreatedAt);
        sb.append(", ").append(eventOccuredAt);
        sb.append(", ").append(sequenceId);
        sb.append(", ").append(occuredAt);
        sb.append(", ").append(walletId);
        sb.append(", ").append(identityId);
        sb.append(", ").append(currencyCode);

        sb.append(")");
        return sb.toString();
    }
}
