/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WalletData implements Serializable {

    private static final long serialVersionUID = 583173734;

    private Long   id;
    private UUID   partyId;
    private String identityId;
    private String walletId;
    private String walletName;

    public WalletData() {}

    public WalletData(WalletData value) {
        this.id = value.id;
        this.partyId = value.partyId;
        this.identityId = value.identityId;
        this.walletId = value.walletId;
        this.walletName = value.walletName;
    }

    public WalletData(
        Long   id,
        UUID   partyId,
        String identityId,
        String walletId,
        String walletName
    ) {
        this.id = id;
        this.partyId = partyId;
        this.identityId = identityId;
        this.walletId = walletId;
        this.walletName = walletName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UUID getPartyId() {
        return this.partyId;
    }

    public void setPartyId(UUID partyId) {
        this.partyId = partyId;
    }

    public String getIdentityId() {
        return this.identityId;
    }

    public void setIdentityId(String identityId) {
        this.identityId = identityId;
    }

    public String getWalletId() {
        return this.walletId;
    }

    public void setWalletId(String walletId) {
        this.walletId = walletId;
    }

    public String getWalletName() {
        return this.walletName;
    }

    public void setWalletName(String walletName) {
        this.walletName = walletName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WalletData other = (WalletData) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (identityId == null) {
            if (other.identityId != null)
                return false;
        }
        else if (!identityId.equals(other.identityId))
            return false;
        if (walletId == null) {
            if (other.walletId != null)
                return false;
        }
        else if (!walletId.equals(other.walletId))
            return false;
        if (walletName == null) {
            if (other.walletName != null)
                return false;
        }
        else if (!walletName.equals(other.walletName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.identityId == null) ? 0 : this.identityId.hashCode());
        result = prime * result + ((this.walletId == null) ? 0 : this.walletId.hashCode());
        result = prime * result + ((this.walletName == null) ? 0 : this.walletName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WalletData (");

        sb.append(id);
        sb.append(", ").append(partyId);
        sb.append(", ").append(identityId);
        sb.append(", ").append(walletId);
        sb.append(", ").append(walletName);

        sb.append(")");
        return sb.toString();
    }
}
