/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WithdrawalData implements Serializable {

    private static final long serialVersionUID = 1702437858;

    private Long id;
    private String withdrawalId;
    private String sourceId;
    private String destinationId;
    private Long amount;
    private String currencyCode;

    public WithdrawalData() {
    }

    public WithdrawalData(WithdrawalData value) {
        this.id = value.id;
        this.withdrawalId = value.withdrawalId;
        this.sourceId = value.sourceId;
        this.destinationId = value.destinationId;
        this.amount = value.amount;
        this.currencyCode = value.currencyCode;
    }

    public WithdrawalData(
            Long id,
            String withdrawalId,
            String sourceId,
            String destinationId,
            Long amount,
            String currencyCode
    ) {
        this.id = id;
        this.withdrawalId = withdrawalId;
        this.sourceId = sourceId;
        this.destinationId = destinationId;
        this.amount = amount;
        this.currencyCode = currencyCode;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWithdrawalId() {
        return this.withdrawalId;
    }

    public void setWithdrawalId(String withdrawalId) {
        this.withdrawalId = withdrawalId;
    }

    public String getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    public String getDestinationId() {
        return this.destinationId;
    }

    public void setDestinationId(String destinationId) {
        this.destinationId = destinationId;
    }

    public Long getAmount() {
        return this.amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final WithdrawalData other = (WithdrawalData) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (withdrawalId == null) {
            if (other.withdrawalId != null)
                return false;
        } else if (!withdrawalId.equals(other.withdrawalId))
            return false;
        if (sourceId == null) {
            if (other.sourceId != null)
                return false;
        } else if (!sourceId.equals(other.sourceId))
            return false;
        if (destinationId == null) {
            if (other.destinationId != null)
                return false;
        } else if (!destinationId.equals(other.destinationId))
            return false;
        if (amount == null) {
            if (other.amount != null)
                return false;
        } else if (!amount.equals(other.amount))
            return false;
        if (currencyCode == null) {
            if (other.currencyCode != null)
                return false;
        } else if (!currencyCode.equals(other.currencyCode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.withdrawalId == null) ? 0 : this.withdrawalId.hashCode());
        result = prime * result + ((this.sourceId == null) ? 0 : this.sourceId.hashCode());
        result = prime * result + ((this.destinationId == null) ? 0 : this.destinationId.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.currencyCode == null) ? 0 : this.currencyCode.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WithdrawalData (");

        sb.append(id);
        sb.append(", ").append(withdrawalId);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(destinationId);
        sb.append(", ").append(amount);
        sb.append(", ").append(currencyCode);

        sb.append(")");
        return sb.toString();
    }
}
