/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables;


import com.rbkmoney.fistful.magista.domain.Indexes;
import com.rbkmoney.fistful.magista.domain.Keys;
import com.rbkmoney.fistful.magista.domain.Mst;
import com.rbkmoney.fistful.magista.domain.tables.records.ChallengeDataRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChallengeData extends TableImpl<ChallengeDataRecord> {

    private static final long serialVersionUID = 1529378727;

    /**
     * The reference instance of <code>mst.challenge_data</code>
     */
    public static final ChallengeData CHALLENGE_DATA = new ChallengeData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChallengeDataRecord> getRecordType() {
        return ChallengeDataRecord.class;
    }

    /**
     * The column <code>mst.challenge_data.id</code>.
     */
    public final TableField<ChallengeDataRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('mst.challenge_data_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>mst.challenge_data.identity_id</code>.
     */
    public final TableField<ChallengeDataRecord, String> IDENTITY_ID = createField("identity_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>mst.challenge_data.challenge_id</code>.
     */
    public final TableField<ChallengeDataRecord, String> CHALLENGE_ID = createField("challenge_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>mst.challenge_data.challenge_class_id</code>.
     */
    public final TableField<ChallengeDataRecord, String> CHALLENGE_CLASS_ID = createField("challenge_class_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * Create a <code>mst.challenge_data</code> table reference
     */
    public ChallengeData() {
        this(DSL.name("challenge_data"), null);
    }

    /**
     * Create an aliased <code>mst.challenge_data</code> table reference
     */
    public ChallengeData(String alias) {
        this(DSL.name(alias), CHALLENGE_DATA);
    }

    /**
     * Create an aliased <code>mst.challenge_data</code> table reference
     */
    public ChallengeData(Name alias) {
        this(alias, CHALLENGE_DATA);
    }

    private ChallengeData(Name alias, Table<ChallengeDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChallengeData(Name alias, Table<ChallengeDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ChallengeData(Table<O> child, ForeignKey<O, ChallengeDataRecord> key) {
        super(child, key, CHALLENGE_DATA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mst.MST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHALLENGE_DATA_PKEY, Indexes.CHALLENGE_DATA_UKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ChallengeDataRecord, Long> getIdentity() {
        return Keys.IDENTITY_CHALLENGE_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ChallengeDataRecord> getPrimaryKey() {
        return Keys.CHALLENGE_DATA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ChallengeDataRecord>> getKeys() {
        return Arrays.<UniqueKey<ChallengeDataRecord>>asList(Keys.CHALLENGE_DATA_PKEY, Keys.CHALLENGE_DATA_UKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChallengeData as(String alias) {
        return new ChallengeData(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChallengeData as(Name alias) {
        return new ChallengeData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChallengeData rename(String name) {
        return new ChallengeData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChallengeData rename(Name name) {
        return new ChallengeData(name, null);
    }
}
