/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables;


import com.rbkmoney.fistful.magista.domain.Indexes;
import com.rbkmoney.fistful.magista.domain.Keys;
import com.rbkmoney.fistful.magista.domain.Mst;
import com.rbkmoney.fistful.magista.domain.enums.WalletEventType;
import com.rbkmoney.fistful.magista.domain.tables.records.WalletEventRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WalletEvent extends TableImpl<WalletEventRecord> {

    private static final long serialVersionUID = 292662133;

    /**
     * The reference instance of <code>mst.wallet_event</code>
     */
    public static final WalletEvent WALLET_EVENT = new WalletEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WalletEventRecord> getRecordType() {
        return WalletEventRecord.class;
    }

    /**
     * The column <code>mst.wallet_event.id</code>.
     */
    public final TableField<WalletEventRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('mst.wallet_event_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>mst.wallet_event.event_id</code>.
     */
    public final TableField<WalletEventRecord, Long> EVENT_ID = createField("event_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>mst.wallet_event.event_type</code>.
     */
    public final TableField<WalletEventRecord, WalletEventType> EVENT_TYPE = createField("event_type", org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(com.rbkmoney.fistful.magista.domain.enums.WalletEventType.class), this, "");

    /**
     * The column <code>mst.wallet_event.event_created_at</code>.
     */
    public final TableField<WalletEventRecord, LocalDateTime> EVENT_CREATED_AT = createField("event_created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>mst.wallet_event.event_occured_at</code>.
     */
    public final TableField<WalletEventRecord, LocalDateTime> EVENT_OCCURED_AT = createField("event_occured_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>mst.wallet_event.sequence_id</code>.
     */
    public final TableField<WalletEventRecord, Integer> SEQUENCE_ID = createField("sequence_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mst.wallet_event.wallet_id</code>.
     */
    public final TableField<WalletEventRecord, String> WALLET_ID = createField("wallet_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>mst.wallet_event.identity_id</code>.
     */
    public final TableField<WalletEventRecord, String> IDENTITY_ID = createField("identity_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>mst.wallet_event.currency_code</code>.
     */
    public final TableField<WalletEventRecord, String> CURRENCY_CODE = createField("currency_code", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>mst.wallet_event</code> table reference
     */
    public WalletEvent() {
        this(DSL.name("wallet_event"), null);
    }

    /**
     * Create an aliased <code>mst.wallet_event</code> table reference
     */
    public WalletEvent(String alias) {
        this(DSL.name(alias), WALLET_EVENT);
    }

    /**
     * Create an aliased <code>mst.wallet_event</code> table reference
     */
    public WalletEvent(Name alias) {
        this(alias, WALLET_EVENT);
    }

    private WalletEvent(Name alias, Table<WalletEventRecord> aliased) {
        this(alias, aliased, null);
    }

    private WalletEvent(Name alias, Table<WalletEventRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> WalletEvent(Table<O> child, ForeignKey<O, WalletEventRecord> key) {
        super(child, key, WALLET_EVENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mst.MST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WALLET_EVENT_PKEY, Indexes.WALLET_EVENT_UKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WalletEventRecord, Long> getIdentity() {
        return Keys.IDENTITY_WALLET_EVENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WalletEventRecord> getPrimaryKey() {
        return Keys.WALLET_EVENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WalletEventRecord>> getKeys() {
        return Arrays.<UniqueKey<WalletEventRecord>>asList(Keys.WALLET_EVENT_PKEY, Keys.WALLET_EVENT_UKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEvent as(String alias) {
        return new WalletEvent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEvent as(Name alias) {
        return new WalletEvent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WalletEvent rename(String name) {
        return new WalletEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WalletEvent rename(Name name) {
        return new WalletEvent(name, null);
    }
}
