/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables;


import com.rbkmoney.fistful.magista.domain.Indexes;
import com.rbkmoney.fistful.magista.domain.Keys;
import com.rbkmoney.fistful.magista.domain.Mst;
import com.rbkmoney.fistful.magista.domain.enums.WithdrawalEventType;
import com.rbkmoney.fistful.magista.domain.enums.WithdrawalStatus;
import com.rbkmoney.fistful.magista.domain.tables.records.WithdrawalEventRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithdrawalEvent extends TableImpl<WithdrawalEventRecord> {

    private static final long serialVersionUID = 1124705600;

    /**
     * The reference instance of <code>mst.withdrawal_event</code>
     */
    public static final WithdrawalEvent WITHDRAWAL_EVENT = new WithdrawalEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithdrawalEventRecord> getRecordType() {
        return WithdrawalEventRecord.class;
    }

    /**
     * The column <code>mst.withdrawal_event.id</code>.
     */
    public final TableField<WithdrawalEventRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('mst.withdrawal_event_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>mst.withdrawal_event.event_id</code>.
     */
    public final TableField<WithdrawalEventRecord, Long> EVENT_ID = createField("event_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>mst.withdrawal_event.event_type</code>.
     */
    public final TableField<WithdrawalEventRecord, WithdrawalEventType> EVENT_TYPE = createField("event_type", org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(com.rbkmoney.fistful.magista.domain.enums.WithdrawalEventType.class), this, "");

    /**
     * The column <code>mst.withdrawal_event.event_created_at</code>.
     */
    public final TableField<WithdrawalEventRecord, LocalDateTime> EVENT_CREATED_AT = createField("event_created_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>mst.withdrawal_event.event_occured_at</code>.
     */
    public final TableField<WithdrawalEventRecord, LocalDateTime> EVENT_OCCURED_AT = createField("event_occured_at", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>mst.withdrawal_event.sequence_id</code>.
     */
    public final TableField<WithdrawalEventRecord, Integer> SEQUENCE_ID = createField("sequence_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mst.withdrawal_event.withdrawal_id</code>.
     */
    public final TableField<WithdrawalEventRecord, String> WITHDRAWAL_ID = createField("withdrawal_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>mst.withdrawal_event.withdrawal_status</code>.
     */
    public final TableField<WithdrawalEventRecord, WithdrawalStatus> WITHDRAWAL_STATUS = createField("withdrawal_status", org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(com.rbkmoney.fistful.magista.domain.enums.WithdrawalStatus.class), this, "");

    /**
     * The column <code>mst.withdrawal_event.fee</code>.
     */
    public final TableField<WithdrawalEventRecord, Long> FEE = createField("fee", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>mst.withdrawal_event</code> table reference
     */
    public WithdrawalEvent() {
        this(DSL.name("withdrawal_event"), null);
    }

    /**
     * Create an aliased <code>mst.withdrawal_event</code> table reference
     */
    public WithdrawalEvent(String alias) {
        this(DSL.name(alias), WITHDRAWAL_EVENT);
    }

    /**
     * Create an aliased <code>mst.withdrawal_event</code> table reference
     */
    public WithdrawalEvent(Name alias) {
        this(alias, WITHDRAWAL_EVENT);
    }

    private WithdrawalEvent(Name alias, Table<WithdrawalEventRecord> aliased) {
        this(alias, aliased, null);
    }

    private WithdrawalEvent(Name alias, Table<WithdrawalEventRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> WithdrawalEvent(Table<O> child, ForeignKey<O, WithdrawalEventRecord> key) {
        super(child, key, WITHDRAWAL_EVENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mst.MST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WITHDRAWAL_EVENT_PKEY, Indexes.WITHDRAWAL_EVENT_UKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WithdrawalEventRecord, Long> getIdentity() {
        return Keys.IDENTITY_WITHDRAWAL_EVENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WithdrawalEventRecord> getPrimaryKey() {
        return Keys.WITHDRAWAL_EVENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WithdrawalEventRecord>> getKeys() {
        return Arrays.<UniqueKey<WithdrawalEventRecord>>asList(Keys.WITHDRAWAL_EVENT_PKEY, Keys.WITHDRAWAL_EVENT_UKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEvent as(String alias) {
        return new WithdrawalEvent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEvent as(Name alias) {
        return new WithdrawalEvent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WithdrawalEvent rename(String name) {
        return new WithdrawalEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WithdrawalEvent rename(Name name) {
        return new WithdrawalEvent(name, null);
    }
}
