/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.records;


import com.rbkmoney.fistful.magista.domain.tables.ChallengeData;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ChallengeDataRecord extends UpdatableRecordImpl<ChallengeDataRecord> implements Record4<Long, String, String, String> {

    private static final long serialVersionUID = 614030477;

    /**
     * Create a detached ChallengeDataRecord
     */
    public ChallengeDataRecord() {
        super(ChallengeData.CHALLENGE_DATA);
    }

    /**
     * Create a detached, initialised ChallengeDataRecord
     */
    public ChallengeDataRecord(Long id, String identityId, String challengeId, String challengeClassId) {
        super(ChallengeData.CHALLENGE_DATA);

        set(0, id);
        set(1, identityId);
        set(2, challengeId);
        set(3, challengeClassId);
    }

    /**
     * Getter for <code>mst.challenge_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.challenge_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.challenge_data.identity_id</code>.
     */
    public String getIdentityId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mst.challenge_data.identity_id</code>.
     */
    public void setIdentityId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.challenge_data.challenge_id</code>.
     */
    public String getChallengeId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mst.challenge_data.challenge_id</code>.
     */
    public void setChallengeId(String value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>mst.challenge_data.challenge_class_id</code>.
     */
    public String getChallengeClassId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>mst.challenge_data.challenge_class_id</code>.
     */
    public void setChallengeClassId(String value) {
        set(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ChallengeData.CHALLENGE_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ChallengeData.CHALLENGE_DATA.IDENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ChallengeData.CHALLENGE_DATA.CHALLENGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ChallengeData.CHALLENGE_DATA.CHALLENGE_CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getChallengeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getChallengeClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getChallengeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getChallengeClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChallengeDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChallengeDataRecord value2(String value) {
        setIdentityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChallengeDataRecord value3(String value) {
        setChallengeId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ChallengeDataRecord value4(String value) {
        setChallengeClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChallengeDataRecord values(Long value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
