/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.records;


import com.rbkmoney.fistful.magista.domain.tables.IdentityData;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdentityDataRecord extends UpdatableRecordImpl<IdentityDataRecord> implements Record6<Long, UUID, String, String, String, String> {

    private static final long serialVersionUID = -1237138686;

    /**
     * Setter for <code>mst.identity_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.identity_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.identity_data.party_id</code>.
     */
    public void setPartyId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.identity_data.party_id</code>.
     */
    public UUID getPartyId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>mst.identity_data.party_contract_id</code>.
     */
    public void setPartyContractId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.identity_data.party_contract_id</code>.
     */
    public String getPartyContractId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mst.identity_data.identity_id</code>.
     */
    public void setIdentityId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.identity_data.identity_id</code>.
     */
    public String getIdentityId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mst.identity_data.identity_provider_id</code>.
     */
    public void setIdentityProviderId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mst.identity_data.identity_provider_id</code>.
     */
    public String getIdentityProviderId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mst.identity_data.identity_class_id</code>.
     */
    public void setIdentityClassId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mst.identity_data.identity_class_id</code>.
     */
    public String getIdentityClassId() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, UUID, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, UUID, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return IdentityData.IDENTITY_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return IdentityData.IDENTITY_DATA.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return IdentityData.IDENTITY_DATA.PARTY_CONTRACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return IdentityData.IDENTITY_DATA.IDENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return IdentityData.IDENTITY_DATA.IDENTITY_PROVIDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return IdentityData.IDENTITY_DATA.IDENTITY_CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPartyContractId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIdentityProviderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getIdentityClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPartyContractId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIdentityProviderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIdentityClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityDataRecord value2(UUID value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityDataRecord value3(String value) {
        setPartyContractId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityDataRecord value4(String value) {
        setIdentityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityDataRecord value5(String value) {
        setIdentityProviderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityDataRecord value6(String value) {
        setIdentityClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityDataRecord values(Long value1, UUID value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IdentityDataRecord
     */
    public IdentityDataRecord() {
        super(IdentityData.IDENTITY_DATA);
    }

    /**
     * Create a detached, initialised IdentityDataRecord
     */
    public IdentityDataRecord(Long id, UUID partyId, String partyContractId, String identityId, String identityProviderId, String identityClassId) {
        super(IdentityData.IDENTITY_DATA);

        set(0, id);
        set(1, partyId);
        set(2, partyContractId);
        set(3, identityId);
        set(4, identityProviderId);
        set(5, identityClassId);
    }
}
