/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.records;


import com.rbkmoney.fistful.magista.domain.tables.WalletData;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WalletDataRecord extends UpdatableRecordImpl<WalletDataRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = -1136168680;

    /**
     * Create a detached WalletDataRecord
     */
    public WalletDataRecord() {
        super(WalletData.WALLET_DATA);
    }

    /**
     * Create a detached, initialised WalletDataRecord
     */
    public WalletDataRecord(Long id, String walletId, String walletName) {
        super(WalletData.WALLET_DATA);

        set(0, id);
        set(1, walletId);
        set(2, walletName);
    }

    /**
     * Getter for <code>mst.wallet_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.wallet_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.wallet_data.wallet_id</code>.
     */
    public String getWalletId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mst.wallet_data.wallet_id</code>.
     */
    public void setWalletId(String value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>mst.wallet_data.wallet_name</code>.
     */
    public String getWalletName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>mst.wallet_data.wallet_name</code>.
     */
    public void setWalletName(String value) {
        set(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return WalletData.WALLET_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WalletData.WALLET_DATA.WALLET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WalletData.WALLET_DATA.WALLET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWalletId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWalletName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWalletId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWalletName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord value2(String value) {
        setWalletId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord value3(String value) {
        setWalletName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
