/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.records;


import com.rbkmoney.fistful.magista.domain.tables.WalletData;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WalletDataRecord extends UpdatableRecordImpl<WalletDataRecord> implements Record5<Long, UUID, String, String, String> {

    private static final long serialVersionUID = 1679109927;

    /**
     * Setter for <code>mst.wallet_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.wallet_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.wallet_data.party_id</code>.
     */
    public void setPartyId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.wallet_data.party_id</code>.
     */
    public UUID getPartyId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>mst.wallet_data.identity_id</code>.
     */
    public void setIdentityId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.wallet_data.identity_id</code>.
     */
    public String getIdentityId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mst.wallet_data.wallet_id</code>.
     */
    public void setWalletId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.wallet_data.wallet_id</code>.
     */
    public String getWalletId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mst.wallet_data.wallet_name</code>.
     */
    public void setWalletName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mst.wallet_data.wallet_name</code>.
     */
    public String getWalletName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, UUID, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, UUID, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return WalletData.WALLET_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return WalletData.WALLET_DATA.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WalletData.WALLET_DATA.IDENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return WalletData.WALLET_DATA.WALLET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return WalletData.WALLET_DATA.WALLET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getWalletId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWalletName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getWalletId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWalletName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord value2(UUID value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord value3(String value) {
        setIdentityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord value4(String value) {
        setWalletId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord value5(String value) {
        setWalletName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletDataRecord values(Long value1, UUID value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WalletDataRecord
     */
    public WalletDataRecord() {
        super(WalletData.WALLET_DATA);
    }

    /**
     * Create a detached, initialised WalletDataRecord
     */
    public WalletDataRecord(Long id, UUID partyId, String identityId, String walletId, String walletName) {
        super(WalletData.WALLET_DATA);

        set(0, id);
        set(1, partyId);
        set(2, identityId);
        set(3, walletId);
        set(4, walletName);
    }
}
