/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.records;


import com.rbkmoney.fistful.magista.domain.enums.WalletEventType;
import com.rbkmoney.fistful.magista.domain.tables.WalletEvent;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WalletEventRecord extends UpdatableRecordImpl<WalletEventRecord> implements Record10<Long, Long, WalletEventType, LocalDateTime, LocalDateTime, Integer, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = -667712588;

    /**
     * Create a detached WalletEventRecord
     */
    public WalletEventRecord() {
        super(WalletEvent.WALLET_EVENT);
    }

    /**
     * Create a detached, initialised WalletEventRecord
     */
    public WalletEventRecord(Long id, Long eventId, WalletEventType eventType, LocalDateTime eventCreatedAt, LocalDateTime eventOccuredAt, Integer sequenceId, LocalDateTime occuredAt, String walletId, String identityId, String currencyCode) {
        super(WalletEvent.WALLET_EVENT);

        set(0, id);
        set(1, eventId);
        set(2, eventType);
        set(3, eventCreatedAt);
        set(4, eventOccuredAt);
        set(5, sequenceId);
        set(6, occuredAt);
        set(7, walletId);
        set(8, identityId);
        set(9, currencyCode);
    }

    /**
     * Getter for <code>mst.wallet_event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.wallet_event.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.wallet_event.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>mst.wallet_event.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.wallet_event.event_type</code>.
     */
    public WalletEventType getEventType() {
        return (WalletEventType) get(2);
    }

    /**
     * Setter for <code>mst.wallet_event.event_type</code>.
     */
    public void setEventType(WalletEventType value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.wallet_event.event_created_at</code>.
     */
    public LocalDateTime getEventCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>mst.wallet_event.event_created_at</code>.
     */
    public void setEventCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.wallet_event.event_occured_at</code>.
     */
    public LocalDateTime getEventOccuredAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>mst.wallet_event.event_occured_at</code>.
     */
    public void setEventOccuredAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>mst.wallet_event.sequence_id</code>.
     */
    public Integer getSequenceId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mst.wallet_event.sequence_id</code>.
     */
    public void setSequenceId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mst.wallet_event.occured_at</code>.
     */
    public LocalDateTime getOccuredAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>mst.wallet_event.occured_at</code>.
     */
    public void setOccuredAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>mst.wallet_event.wallet_id</code>.
     */
    public String getWalletId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mst.wallet_event.wallet_id</code>.
     */
    public void setWalletId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mst.wallet_event.identity_id</code>.
     */
    public String getIdentityId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mst.wallet_event.identity_id</code>.
     */
    public void setIdentityId(String value) {
        set(8, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>mst.wallet_event.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>mst.wallet_event.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(9, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, WalletEventType, LocalDateTime, LocalDateTime, Integer, LocalDateTime, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, WalletEventType, LocalDateTime, LocalDateTime, Integer, LocalDateTime, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return WalletEvent.WALLET_EVENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return WalletEvent.WALLET_EVENT.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<WalletEventType> field3() {
        return WalletEvent.WALLET_EVENT.EVENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return WalletEvent.WALLET_EVENT.EVENT_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return WalletEvent.WALLET_EVENT.EVENT_OCCURED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return WalletEvent.WALLET_EVENT.SEQUENCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return WalletEvent.WALLET_EVENT.OCCURED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return WalletEvent.WALLET_EVENT.WALLET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return WalletEvent.WALLET_EVENT.IDENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return WalletEvent.WALLET_EVENT.CURRENCY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventType component3() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getEventCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getEventOccuredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getSequenceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getOccuredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getWalletId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventType value3() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getEventCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getEventOccuredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSequenceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getOccuredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getWalletId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value3(WalletEventType value) {
        setEventType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value4(LocalDateTime value) {
        setEventCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value5(LocalDateTime value) {
        setEventOccuredAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value6(Integer value) {
        setSequenceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value7(LocalDateTime value) {
        setOccuredAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value8(String value) {
        setWalletId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value9(String value) {
        setIdentityId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord value10(String value) {
        setCurrencyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WalletEventRecord values(Long value1, Long value2, WalletEventType value3, LocalDateTime value4, LocalDateTime value5, Integer value6, LocalDateTime value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
}
