/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.records;


import com.rbkmoney.fistful.magista.domain.tables.WithdrawalData;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WithdrawalDataRecord extends UpdatableRecordImpl<WithdrawalDataRecord> implements Record6<Long, String, String, String, Long, String> {

    private static final long serialVersionUID = -612381777;

    /**
     * Create a detached WithdrawalDataRecord
     */
    public WithdrawalDataRecord() {
        super(WithdrawalData.WITHDRAWAL_DATA);
    }

    /**
     * Create a detached, initialised WithdrawalDataRecord
     */
    public WithdrawalDataRecord(Long id, String withdrawalId, String sourceId, String destinationId, Long amount, String currencyCode) {
        super(WithdrawalData.WITHDRAWAL_DATA);

        set(0, id);
        set(1, withdrawalId);
        set(2, sourceId);
        set(3, destinationId);
        set(4, amount);
        set(5, currencyCode);
    }

    /**
     * Getter for <code>mst.withdrawal_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.withdrawal_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.withdrawal_id</code>.
     */
    public String getWithdrawalId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mst.withdrawal_data.withdrawal_id</code>.
     */
    public void setWithdrawalId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.source_id</code>.
     */
    public String getSourceId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mst.withdrawal_data.source_id</code>.
     */
    public void setSourceId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.destination_id</code>.
     */
    public String getDestinationId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mst.withdrawal_data.destination_id</code>.
     */
    public void setDestinationId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>mst.withdrawal_data.amount</code>.
     */
    public void setAmount(Long value) {
        set(4, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>mst.withdrawal_data.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>mst.withdrawal_data.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return WithdrawalData.WITHDRAWAL_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return WithdrawalData.WITHDRAWAL_DATA.WITHDRAWAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WithdrawalData.WITHDRAWAL_DATA.SOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return WithdrawalData.WITHDRAWAL_DATA.DESTINATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return WithdrawalData.WITHDRAWAL_DATA.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return WithdrawalData.WITHDRAWAL_DATA.CURRENCY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWithdrawalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDestinationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWithdrawalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDestinationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value2(String value) {
        setWithdrawalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value3(String value) {
        setSourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value4(String value) {
        setDestinationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value5(Long value) {
        setAmount(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value6(String value) {
        setCurrencyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord values(Long value1, String value2, String value3, String value4, Long value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }
}
