/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.records;


import com.rbkmoney.fistful.magista.domain.tables.WithdrawalData;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithdrawalDataRecord extends UpdatableRecordImpl<WithdrawalDataRecord> implements Record8<Long, UUID, String, String, String, String, Long, String> {

    private static final long serialVersionUID = -1731817440;

    /**
     * Setter for <code>mst.withdrawal_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.withdrawal_data.party_id</code>.
     */
    public void setPartyId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.party_id</code>.
     */
    public UUID getPartyId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>mst.withdrawal_data.identity_id</code>.
     */
    public void setIdentityId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.identity_id</code>.
     */
    public String getIdentityId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mst.withdrawal_data.withdrawal_id</code>.
     */
    public void setWithdrawalId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.withdrawal_id</code>.
     */
    public String getWithdrawalId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mst.withdrawal_data.wallet_id</code>.
     */
    public void setWalletId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.wallet_id</code>.
     */
    public String getWalletId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mst.withdrawal_data.destination_id</code>.
     */
    public void setDestinationId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.destination_id</code>.
     */
    public String getDestinationId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mst.withdrawal_data.amount</code>.
     */
    public void setAmount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>mst.withdrawal_data.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mst.withdrawal_data.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, UUID, String, String, String, String, Long, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, UUID, String, String, String, String, Long, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return WithdrawalData.WITHDRAWAL_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return WithdrawalData.WITHDRAWAL_DATA.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WithdrawalData.WITHDRAWAL_DATA.IDENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return WithdrawalData.WITHDRAWAL_DATA.WITHDRAWAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return WithdrawalData.WITHDRAWAL_DATA.WALLET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return WithdrawalData.WITHDRAWAL_DATA.DESTINATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return WithdrawalData.WITHDRAWAL_DATA.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return WithdrawalData.WITHDRAWAL_DATA.CURRENCY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getWithdrawalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWalletId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDestinationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIdentityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getWithdrawalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWalletId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDestinationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value2(UUID value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value3(String value) {
        setIdentityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value4(String value) {
        setWithdrawalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value5(String value) {
        setWalletId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value6(String value) {
        setDestinationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value7(Long value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord value8(String value) {
        setCurrencyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalDataRecord values(Long value1, UUID value2, String value3, String value4, String value5, String value6, Long value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WithdrawalDataRecord
     */
    public WithdrawalDataRecord() {
        super(WithdrawalData.WITHDRAWAL_DATA);
    }

    /**
     * Create a detached, initialised WithdrawalDataRecord
     */
    public WithdrawalDataRecord(Long id, UUID partyId, String identityId, String withdrawalId, String walletId, String destinationId, Long amount, String currencyCode) {
        super(WithdrawalData.WITHDRAWAL_DATA);

        set(0, id);
        set(1, partyId);
        set(2, identityId);
        set(3, withdrawalId);
        set(4, walletId);
        set(5, destinationId);
        set(6, amount);
        set(7, currencyCode);
    }
}
