/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain.tables.records;


import com.rbkmoney.fistful.magista.domain.enums.WithdrawalEventType;
import com.rbkmoney.fistful.magista.domain.enums.WithdrawalStatus;
import com.rbkmoney.fistful.magista.domain.tables.WithdrawalEvent;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WithdrawalEventRecord extends UpdatableRecordImpl<WithdrawalEventRecord> implements Record9<Long, Long, WithdrawalEventType, LocalDateTime, LocalDateTime, Integer, String, WithdrawalStatus, Long> {

    private static final long serialVersionUID = 618463830;

    /**
     * Setter for <code>mst.withdrawal_event.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>mst.withdrawal_event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>mst.withdrawal_event.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>mst.withdrawal_event.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>mst.withdrawal_event.event_type</code>.
     */
    public void setEventType(WithdrawalEventType value) {
        set(2, value);
    }

    /**
     * Getter for <code>mst.withdrawal_event.event_type</code>.
     */
    public WithdrawalEventType getEventType() {
        return (WithdrawalEventType) get(2);
    }

    /**
     * Setter for <code>mst.withdrawal_event.event_created_at</code>.
     */
    public void setEventCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>mst.withdrawal_event.event_created_at</code>.
     */
    public LocalDateTime getEventCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>mst.withdrawal_event.event_occured_at</code>.
     */
    public void setEventOccuredAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>mst.withdrawal_event.event_occured_at</code>.
     */
    public LocalDateTime getEventOccuredAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>mst.withdrawal_event.sequence_id</code>.
     */
    public void setSequenceId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mst.withdrawal_event.sequence_id</code>.
     */
    public Integer getSequenceId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mst.withdrawal_event.withdrawal_id</code>.
     */
    public void setWithdrawalId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mst.withdrawal_event.withdrawal_id</code>.
     */
    public String getWithdrawalId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mst.withdrawal_event.withdrawal_status</code>.
     */
    public void setWithdrawalStatus(WithdrawalStatus value) {
        set(7, value);
    }

    /**
     * Getter for <code>mst.withdrawal_event.withdrawal_status</code>.
     */
    public WithdrawalStatus getWithdrawalStatus() {
        return (WithdrawalStatus) get(7);
    }

    /**
     * Setter for <code>mst.withdrawal_event.fee</code>.
     */
    public void setFee(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>mst.withdrawal_event.fee</code>.
     */
    public Long getFee() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, WithdrawalEventType, LocalDateTime, LocalDateTime, Integer, String, WithdrawalStatus, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, WithdrawalEventType, LocalDateTime, LocalDateTime, Integer, String, WithdrawalStatus, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return WithdrawalEvent.WITHDRAWAL_EVENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return WithdrawalEvent.WITHDRAWAL_EVENT.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<WithdrawalEventType> field3() {
        return WithdrawalEvent.WITHDRAWAL_EVENT.EVENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return WithdrawalEvent.WITHDRAWAL_EVENT.EVENT_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return WithdrawalEvent.WITHDRAWAL_EVENT.EVENT_OCCURED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return WithdrawalEvent.WITHDRAWAL_EVENT.SEQUENCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return WithdrawalEvent.WITHDRAWAL_EVENT.WITHDRAWAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<WithdrawalStatus> field8() {
        return WithdrawalEvent.WITHDRAWAL_EVENT.WITHDRAWAL_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return WithdrawalEvent.WITHDRAWAL_EVENT.FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventType component3() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getEventCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getEventOccuredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getSequenceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWithdrawalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalStatus component8() {
        return getWithdrawalStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventType value3() {
        return getEventType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getEventCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getEventOccuredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSequenceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWithdrawalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalStatus value8() {
        return getWithdrawalStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord value3(WithdrawalEventType value) {
        setEventType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord value4(LocalDateTime value) {
        setEventCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord value5(LocalDateTime value) {
        setEventOccuredAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord value6(Integer value) {
        setSequenceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord value7(String value) {
        setWithdrawalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord value8(WithdrawalStatus value) {
        setWithdrawalStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord value9(Long value) {
        setFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalEventRecord values(Long value1, Long value2, WithdrawalEventType value3, LocalDateTime value4, LocalDateTime value5, Integer value6, String value7, WithdrawalStatus value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WithdrawalEventRecord
     */
    public WithdrawalEventRecord() {
        super(WithdrawalEvent.WITHDRAWAL_EVENT);
    }

    /**
     * Create a detached, initialised WithdrawalEventRecord
     */
    public WithdrawalEventRecord(Long id, Long eventId, WithdrawalEventType eventType, LocalDateTime eventCreatedAt, LocalDateTime eventOccuredAt, Integer sequenceId, String withdrawalId, WithdrawalStatus withdrawalStatus, Long fee) {
        super(WithdrawalEvent.WITHDRAWAL_EVENT);

        set(0, id);
        set(1, eventId);
        set(2, eventType);
        set(3, eventCreatedAt);
        set(4, eventOccuredAt);
        set(5, sequenceId);
        set(6, withdrawalId);
        set(7, withdrawalStatus);
        set(8, fee);
    }
}
