/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain;


import com.rbkmoney.fistful.magista.domain.tables.ChallengeData;
import com.rbkmoney.fistful.magista.domain.tables.ChallengeEvent;
import com.rbkmoney.fistful.magista.domain.tables.IdentityData;
import com.rbkmoney.fistful.magista.domain.tables.IdentityEvent;
import com.rbkmoney.fistful.magista.domain.tables.WalletData;
import com.rbkmoney.fistful.magista.domain.tables.WalletEvent;
import com.rbkmoney.fistful.magista.domain.tables.WithdrawalData;
import com.rbkmoney.fistful.magista.domain.tables.WithdrawalEvent;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>mst</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CHALLENGE_DATA_PKEY = Indexes0.CHALLENGE_DATA_PKEY;
    public static final Index CHALLENGE_DATA_UKEY = Indexes0.CHALLENGE_DATA_UKEY;
    public static final Index CHALLENGE_EVENT_PKEY = Indexes0.CHALLENGE_EVENT_PKEY;
    public static final Index CHALLENGE_EVENT_UKEY = Indexes0.CHALLENGE_EVENT_UKEY;
    public static final Index IDENTITY_DATA_PKEY = Indexes0.IDENTITY_DATA_PKEY;
    public static final Index IDENTITY_DATA_UKEY = Indexes0.IDENTITY_DATA_UKEY;
    public static final Index IDENTITY_EVENT_PKEY = Indexes0.IDENTITY_EVENT_PKEY;
    public static final Index IDENTITY_EVENT_UKEY = Indexes0.IDENTITY_EVENT_UKEY;
    public static final Index WALLET_DATA_PKEY = Indexes0.WALLET_DATA_PKEY;
    public static final Index WALLET_DATA_UKEY = Indexes0.WALLET_DATA_UKEY;
    public static final Index WALLET_EVENT_PKEY = Indexes0.WALLET_EVENT_PKEY;
    public static final Index WALLET_EVENT_UKEY = Indexes0.WALLET_EVENT_UKEY;
    public static final Index WITHDRAWAL_DATA_PKEY = Indexes0.WITHDRAWAL_DATA_PKEY;
    public static final Index WITHDRAWAL_DATA_UKEY = Indexes0.WITHDRAWAL_DATA_UKEY;
    public static final Index WITHDRAWAL_EVENT_PKEY = Indexes0.WITHDRAWAL_EVENT_PKEY;
    public static final Index WITHDRAWAL_EVENT_UKEY = Indexes0.WITHDRAWAL_EVENT_UKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CHALLENGE_DATA_PKEY = Internal.createIndex("challenge_data_pkey", ChallengeData.CHALLENGE_DATA, new OrderField[] { ChallengeData.CHALLENGE_DATA.ID }, true);
        public static Index CHALLENGE_DATA_UKEY = Internal.createIndex("challenge_data_ukey", ChallengeData.CHALLENGE_DATA, new OrderField[] { ChallengeData.CHALLENGE_DATA.IDENTITY_ID, ChallengeData.CHALLENGE_DATA.CHALLENGE_ID }, true);
        public static Index CHALLENGE_EVENT_PKEY = Internal.createIndex("challenge_event_pkey", ChallengeEvent.CHALLENGE_EVENT, new OrderField[] { ChallengeEvent.CHALLENGE_EVENT.ID }, true);
        public static Index CHALLENGE_EVENT_UKEY = Internal.createIndex("challenge_event_ukey", ChallengeEvent.CHALLENGE_EVENT, new OrderField[] { ChallengeEvent.CHALLENGE_EVENT.EVENT_ID, ChallengeEvent.CHALLENGE_EVENT.SEQUENCE_ID }, true);
        public static Index IDENTITY_DATA_PKEY = Internal.createIndex("identity_data_pkey", IdentityData.IDENTITY_DATA, new OrderField[] { IdentityData.IDENTITY_DATA.ID }, true);
        public static Index IDENTITY_DATA_UKEY = Internal.createIndex("identity_data_ukey", IdentityData.IDENTITY_DATA, new OrderField[] { IdentityData.IDENTITY_DATA.IDENTITY_ID }, true);
        public static Index IDENTITY_EVENT_PKEY = Internal.createIndex("identity_event_pkey", IdentityEvent.IDENTITY_EVENT, new OrderField[] { IdentityEvent.IDENTITY_EVENT.ID }, true);
        public static Index IDENTITY_EVENT_UKEY = Internal.createIndex("identity_event_ukey", IdentityEvent.IDENTITY_EVENT, new OrderField[] { IdentityEvent.IDENTITY_EVENT.EVENT_ID, IdentityEvent.IDENTITY_EVENT.SEQUENCE_ID }, true);
        public static Index WALLET_DATA_PKEY = Internal.createIndex("wallet_data_pkey", WalletData.WALLET_DATA, new OrderField[] { WalletData.WALLET_DATA.ID }, true);
        public static Index WALLET_DATA_UKEY = Internal.createIndex("wallet_data_ukey", WalletData.WALLET_DATA, new OrderField[] { WalletData.WALLET_DATA.WALLET_ID }, true);
        public static Index WALLET_EVENT_PKEY = Internal.createIndex("wallet_event_pkey", WalletEvent.WALLET_EVENT, new OrderField[] { WalletEvent.WALLET_EVENT.ID }, true);
        public static Index WALLET_EVENT_UKEY = Internal.createIndex("wallet_event_ukey", WalletEvent.WALLET_EVENT, new OrderField[] { WalletEvent.WALLET_EVENT.EVENT_ID, WalletEvent.WALLET_EVENT.SEQUENCE_ID }, true);
        public static Index WITHDRAWAL_DATA_PKEY = Internal.createIndex("withdrawal_data_pkey", WithdrawalData.WITHDRAWAL_DATA, new OrderField[] { WithdrawalData.WITHDRAWAL_DATA.ID }, true);
        public static Index WITHDRAWAL_DATA_UKEY = Internal.createIndex("withdrawal_data_ukey", WithdrawalData.WITHDRAWAL_DATA, new OrderField[] { WithdrawalData.WITHDRAWAL_DATA.WITHDRAWAL_ID }, true);
        public static Index WITHDRAWAL_EVENT_PKEY = Internal.createIndex("withdrawal_event_pkey", WithdrawalEvent.WITHDRAWAL_EVENT, new OrderField[] { WithdrawalEvent.WITHDRAWAL_EVENT.ID }, true);
        public static Index WITHDRAWAL_EVENT_UKEY = Internal.createIndex("withdrawal_event_ukey", WithdrawalEvent.WITHDRAWAL_EVENT, new OrderField[] { WithdrawalEvent.WITHDRAWAL_EVENT.EVENT_ID, WithdrawalEvent.WITHDRAWAL_EVENT.SEQUENCE_ID }, true);
    }
}
