/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain;


import com.rbkmoney.fistful.magista.domain.tables.ChallengeData;
import com.rbkmoney.fistful.magista.domain.tables.ChallengeEvent;
import com.rbkmoney.fistful.magista.domain.tables.IdentityData;
import com.rbkmoney.fistful.magista.domain.tables.IdentityEvent;
import com.rbkmoney.fistful.magista.domain.tables.WalletData;
import com.rbkmoney.fistful.magista.domain.tables.WalletEvent;
import com.rbkmoney.fistful.magista.domain.tables.WithdrawalData;
import com.rbkmoney.fistful.magista.domain.tables.WithdrawalEvent;
import com.rbkmoney.fistful.magista.domain.tables.records.ChallengeDataRecord;
import com.rbkmoney.fistful.magista.domain.tables.records.ChallengeEventRecord;
import com.rbkmoney.fistful.magista.domain.tables.records.IdentityDataRecord;
import com.rbkmoney.fistful.magista.domain.tables.records.IdentityEventRecord;
import com.rbkmoney.fistful.magista.domain.tables.records.WalletDataRecord;
import com.rbkmoney.fistful.magista.domain.tables.records.WalletEventRecord;
import com.rbkmoney.fistful.magista.domain.tables.records.WithdrawalDataRecord;
import com.rbkmoney.fistful.magista.domain.tables.records.WithdrawalEventRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>mst</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ChallengeDataRecord, Long> IDENTITY_CHALLENGE_DATA = Identities0.IDENTITY_CHALLENGE_DATA;
    public static final Identity<ChallengeEventRecord, Long> IDENTITY_CHALLENGE_EVENT = Identities0.IDENTITY_CHALLENGE_EVENT;
    public static final Identity<IdentityDataRecord, Long> IDENTITY_IDENTITY_DATA = Identities0.IDENTITY_IDENTITY_DATA;
    public static final Identity<IdentityEventRecord, Long> IDENTITY_IDENTITY_EVENT = Identities0.IDENTITY_IDENTITY_EVENT;
    public static final Identity<WalletDataRecord, Long> IDENTITY_WALLET_DATA = Identities0.IDENTITY_WALLET_DATA;
    public static final Identity<WalletEventRecord, Long> IDENTITY_WALLET_EVENT = Identities0.IDENTITY_WALLET_EVENT;
    public static final Identity<WithdrawalDataRecord, Long> IDENTITY_WITHDRAWAL_DATA = Identities0.IDENTITY_WITHDRAWAL_DATA;
    public static final Identity<WithdrawalEventRecord, Long> IDENTITY_WITHDRAWAL_EVENT = Identities0.IDENTITY_WITHDRAWAL_EVENT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChallengeDataRecord> CHALLENGE_DATA_PKEY = UniqueKeys0.CHALLENGE_DATA_PKEY;
    public static final UniqueKey<ChallengeDataRecord> CHALLENGE_DATA_UKEY = UniqueKeys0.CHALLENGE_DATA_UKEY;
    public static final UniqueKey<ChallengeEventRecord> CHALLENGE_EVENT_PKEY = UniqueKeys0.CHALLENGE_EVENT_PKEY;
    public static final UniqueKey<ChallengeEventRecord> CHALLENGE_EVENT_UKEY = UniqueKeys0.CHALLENGE_EVENT_UKEY;
    public static final UniqueKey<IdentityDataRecord> IDENTITY_DATA_PKEY = UniqueKeys0.IDENTITY_DATA_PKEY;
    public static final UniqueKey<IdentityDataRecord> IDENTITY_DATA_UKEY = UniqueKeys0.IDENTITY_DATA_UKEY;
    public static final UniqueKey<IdentityEventRecord> IDENTITY_EVENT_PKEY = UniqueKeys0.IDENTITY_EVENT_PKEY;
    public static final UniqueKey<IdentityEventRecord> IDENTITY_EVENT_UKEY = UniqueKeys0.IDENTITY_EVENT_UKEY;
    public static final UniqueKey<WalletDataRecord> WALLET_DATA_PKEY = UniqueKeys0.WALLET_DATA_PKEY;
    public static final UniqueKey<WalletDataRecord> WALLET_DATA_UKEY = UniqueKeys0.WALLET_DATA_UKEY;
    public static final UniqueKey<WalletEventRecord> WALLET_EVENT_PKEY = UniqueKeys0.WALLET_EVENT_PKEY;
    public static final UniqueKey<WalletEventRecord> WALLET_EVENT_UKEY = UniqueKeys0.WALLET_EVENT_UKEY;
    public static final UniqueKey<WithdrawalDataRecord> WITHDRAWAL_DATA_PKEY = UniqueKeys0.WITHDRAWAL_DATA_PKEY;
    public static final UniqueKey<WithdrawalDataRecord> WITHDRAWAL_DATA_UKEY = UniqueKeys0.WITHDRAWAL_DATA_UKEY;
    public static final UniqueKey<WithdrawalEventRecord> WITHDRAWAL_EVENT_PKEY = UniqueKeys0.WITHDRAWAL_EVENT_PKEY;
    public static final UniqueKey<WithdrawalEventRecord> WITHDRAWAL_EVENT_UKEY = UniqueKeys0.WITHDRAWAL_EVENT_UKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ChallengeDataRecord, Long> IDENTITY_CHALLENGE_DATA = Internal.createIdentity(ChallengeData.CHALLENGE_DATA, ChallengeData.CHALLENGE_DATA.ID);
        public static Identity<ChallengeEventRecord, Long> IDENTITY_CHALLENGE_EVENT = Internal.createIdentity(ChallengeEvent.CHALLENGE_EVENT, ChallengeEvent.CHALLENGE_EVENT.ID);
        public static Identity<IdentityDataRecord, Long> IDENTITY_IDENTITY_DATA = Internal.createIdentity(IdentityData.IDENTITY_DATA, IdentityData.IDENTITY_DATA.ID);
        public static Identity<IdentityEventRecord, Long> IDENTITY_IDENTITY_EVENT = Internal.createIdentity(IdentityEvent.IDENTITY_EVENT, IdentityEvent.IDENTITY_EVENT.ID);
        public static Identity<WalletDataRecord, Long> IDENTITY_WALLET_DATA = Internal.createIdentity(WalletData.WALLET_DATA, WalletData.WALLET_DATA.ID);
        public static Identity<WalletEventRecord, Long> IDENTITY_WALLET_EVENT = Internal.createIdentity(WalletEvent.WALLET_EVENT, WalletEvent.WALLET_EVENT.ID);
        public static Identity<WithdrawalDataRecord, Long> IDENTITY_WITHDRAWAL_DATA = Internal.createIdentity(WithdrawalData.WITHDRAWAL_DATA, WithdrawalData.WITHDRAWAL_DATA.ID);
        public static Identity<WithdrawalEventRecord, Long> IDENTITY_WITHDRAWAL_EVENT = Internal.createIdentity(WithdrawalEvent.WITHDRAWAL_EVENT, WithdrawalEvent.WITHDRAWAL_EVENT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ChallengeDataRecord> CHALLENGE_DATA_PKEY = Internal.createUniqueKey(ChallengeData.CHALLENGE_DATA, "challenge_data_pkey", ChallengeData.CHALLENGE_DATA.ID);
        public static final UniqueKey<ChallengeDataRecord> CHALLENGE_DATA_UKEY = Internal.createUniqueKey(ChallengeData.CHALLENGE_DATA, "challenge_data_ukey", ChallengeData.CHALLENGE_DATA.IDENTITY_ID, ChallengeData.CHALLENGE_DATA.CHALLENGE_ID);
        public static final UniqueKey<ChallengeEventRecord> CHALLENGE_EVENT_PKEY = Internal.createUniqueKey(ChallengeEvent.CHALLENGE_EVENT, "challenge_event_pkey", ChallengeEvent.CHALLENGE_EVENT.ID);
        public static final UniqueKey<ChallengeEventRecord> CHALLENGE_EVENT_UKEY = Internal.createUniqueKey(ChallengeEvent.CHALLENGE_EVENT, "challenge_event_ukey", ChallengeEvent.CHALLENGE_EVENT.EVENT_ID, ChallengeEvent.CHALLENGE_EVENT.SEQUENCE_ID);
        public static final UniqueKey<IdentityDataRecord> IDENTITY_DATA_PKEY = Internal.createUniqueKey(IdentityData.IDENTITY_DATA, "identity_data_pkey", IdentityData.IDENTITY_DATA.ID);
        public static final UniqueKey<IdentityDataRecord> IDENTITY_DATA_UKEY = Internal.createUniqueKey(IdentityData.IDENTITY_DATA, "identity_data_ukey", IdentityData.IDENTITY_DATA.IDENTITY_ID);
        public static final UniqueKey<IdentityEventRecord> IDENTITY_EVENT_PKEY = Internal.createUniqueKey(IdentityEvent.IDENTITY_EVENT, "identity_event_pkey", IdentityEvent.IDENTITY_EVENT.ID);
        public static final UniqueKey<IdentityEventRecord> IDENTITY_EVENT_UKEY = Internal.createUniqueKey(IdentityEvent.IDENTITY_EVENT, "identity_event_ukey", IdentityEvent.IDENTITY_EVENT.EVENT_ID, IdentityEvent.IDENTITY_EVENT.SEQUENCE_ID);
        public static final UniqueKey<WalletDataRecord> WALLET_DATA_PKEY = Internal.createUniqueKey(WalletData.WALLET_DATA, "wallet_data_pkey", WalletData.WALLET_DATA.ID);
        public static final UniqueKey<WalletDataRecord> WALLET_DATA_UKEY = Internal.createUniqueKey(WalletData.WALLET_DATA, "wallet_data_ukey", WalletData.WALLET_DATA.WALLET_ID);
        public static final UniqueKey<WalletEventRecord> WALLET_EVENT_PKEY = Internal.createUniqueKey(WalletEvent.WALLET_EVENT, "wallet_event_pkey", WalletEvent.WALLET_EVENT.ID);
        public static final UniqueKey<WalletEventRecord> WALLET_EVENT_UKEY = Internal.createUniqueKey(WalletEvent.WALLET_EVENT, "wallet_event_ukey", WalletEvent.WALLET_EVENT.EVENT_ID, WalletEvent.WALLET_EVENT.SEQUENCE_ID);
        public static final UniqueKey<WithdrawalDataRecord> WITHDRAWAL_DATA_PKEY = Internal.createUniqueKey(WithdrawalData.WITHDRAWAL_DATA, "withdrawal_data_pkey", WithdrawalData.WITHDRAWAL_DATA.ID);
        public static final UniqueKey<WithdrawalDataRecord> WITHDRAWAL_DATA_UKEY = Internal.createUniqueKey(WithdrawalData.WITHDRAWAL_DATA, "withdrawal_data_ukey", WithdrawalData.WITHDRAWAL_DATA.WITHDRAWAL_ID);
        public static final UniqueKey<WithdrawalEventRecord> WITHDRAWAL_EVENT_PKEY = Internal.createUniqueKey(WithdrawalEvent.WITHDRAWAL_EVENT, "withdrawal_event_pkey", WithdrawalEvent.WITHDRAWAL_EVENT.ID);
        public static final UniqueKey<WithdrawalEventRecord> WITHDRAWAL_EVENT_UKEY = Internal.createUniqueKey(WithdrawalEvent.WITHDRAWAL_EVENT, "withdrawal_event_ukey", WithdrawalEvent.WITHDRAWAL_EVENT.EVENT_ID, WithdrawalEvent.WITHDRAWAL_EVENT.SEQUENCE_ID);
    }
}
