/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain;


import com.rbkmoney.fistful.magista.domain.tables.ChallengeData;
import com.rbkmoney.fistful.magista.domain.tables.ChallengeEvent;
import com.rbkmoney.fistful.magista.domain.tables.IdentityData;
import com.rbkmoney.fistful.magista.domain.tables.IdentityEvent;
import com.rbkmoney.fistful.magista.domain.tables.WalletData;
import com.rbkmoney.fistful.magista.domain.tables.WalletEvent;
import com.rbkmoney.fistful.magista.domain.tables.WithdrawalData;
import com.rbkmoney.fistful.magista.domain.tables.WithdrawalEvent;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mst extends SchemaImpl {

    private static final long serialVersionUID = 1410319013;

    /**
     * The reference instance of <code>mst</code>
     */
    public static final Mst MST = new Mst();

    /**
     * The table <code>mst.challenge_data</code>.
     */
    public final ChallengeData CHALLENGE_DATA = com.rbkmoney.fistful.magista.domain.tables.ChallengeData.CHALLENGE_DATA;

    /**
     * The table <code>mst.challenge_event</code>.
     */
    public final ChallengeEvent CHALLENGE_EVENT = com.rbkmoney.fistful.magista.domain.tables.ChallengeEvent.CHALLENGE_EVENT;

    /**
     * The table <code>mst.identity_data</code>.
     */
    public final IdentityData IDENTITY_DATA = com.rbkmoney.fistful.magista.domain.tables.IdentityData.IDENTITY_DATA;

    /**
     * The table <code>mst.identity_event</code>.
     */
    public final IdentityEvent IDENTITY_EVENT = com.rbkmoney.fistful.magista.domain.tables.IdentityEvent.IDENTITY_EVENT;

    /**
     * The table <code>mst.wallet_data</code>.
     */
    public final WalletData WALLET_DATA = com.rbkmoney.fistful.magista.domain.tables.WalletData.WALLET_DATA;

    /**
     * The table <code>mst.wallet_event</code>.
     */
    public final WalletEvent WALLET_EVENT = com.rbkmoney.fistful.magista.domain.tables.WalletEvent.WALLET_EVENT;

    /**
     * The table <code>mst.withdrawal_data</code>.
     */
    public final WithdrawalData WITHDRAWAL_DATA = com.rbkmoney.fistful.magista.domain.tables.WithdrawalData.WITHDRAWAL_DATA;

    /**
     * The table <code>mst.withdrawal_event</code>.
     */
    public final WithdrawalEvent WITHDRAWAL_EVENT = com.rbkmoney.fistful.magista.domain.tables.WithdrawalEvent.WITHDRAWAL_EVENT;

    /**
     * No further instances allowed
     */
    private Mst() {
        super("mst", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CHALLENGE_DATA_ID_SEQ,
            Sequences.CHALLENGE_EVENT_ID_SEQ,
            Sequences.IDENTITY_DATA_ID_SEQ,
            Sequences.IDENTITY_EVENT_ID_SEQ,
            Sequences.WALLET_DATA_ID_SEQ,
            Sequences.WALLET_EVENT_ID_SEQ,
            Sequences.WITHDRAWAL_DATA_ID_SEQ,
            Sequences.WITHDRAWAL_EVENT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ChallengeData.CHALLENGE_DATA,
            ChallengeEvent.CHALLENGE_EVENT,
            IdentityData.IDENTITY_DATA,
            IdentityEvent.IDENTITY_EVENT,
            WalletData.WALLET_DATA,
            WalletEvent.WALLET_EVENT,
            WithdrawalData.WITHDRAWAL_DATA,
            WithdrawalEvent.WITHDRAWAL_EVENT);
    }
}
