/*
 * This file is generated by jOOQ.
 */
package com.rbkmoney.fistful.magista.domain;


import com.rbkmoney.fistful.magista.domain.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mst
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mst.challenge_data</code>.
     */
    public static final ChallengeData CHALLENGE_DATA = com.rbkmoney.fistful.magista.domain.tables.ChallengeData.CHALLENGE_DATA;

    /**
     * The table <code>mst.challenge_event</code>.
     */
    public static final ChallengeEvent CHALLENGE_EVENT = com.rbkmoney.fistful.magista.domain.tables.ChallengeEvent.CHALLENGE_EVENT;

    /**
     * The table <code>mst.deposit</code>.
     */
    public static final Deposit DEPOSIT = com.rbkmoney.fistful.magista.domain.tables.Deposit.DEPOSIT;

    /**
     * The table <code>mst.identity_data</code>.
     */
    public static final IdentityData IDENTITY_DATA = com.rbkmoney.fistful.magista.domain.tables.IdentityData.IDENTITY_DATA;

    /**
     * The table <code>mst.identity_event</code>.
     */
    public static final IdentityEvent IDENTITY_EVENT = com.rbkmoney.fistful.magista.domain.tables.IdentityEvent.IDENTITY_EVENT;

    /**
     * The table <code>mst.wallet_data</code>.
     */
    public static final WalletData WALLET_DATA = com.rbkmoney.fistful.magista.domain.tables.WalletData.WALLET_DATA;

    /**
     * The table <code>mst.wallet_event</code>.
     */
    public static final WalletEvent WALLET_EVENT = com.rbkmoney.fistful.magista.domain.tables.WalletEvent.WALLET_EVENT;

    /**
     * The table <code>mst.withdrawal_data</code>.
     */
    public static final WithdrawalData WITHDRAWAL_DATA = com.rbkmoney.fistful.magista.domain.tables.WithdrawalData.WITHDRAWAL_DATA;

    /**
     * The table <code>mst.withdrawal_event</code>.
     */
    public static final WithdrawalEvent WITHDRAWAL_EVENT = com.rbkmoney.fistful.magista.domain.tables.WithdrawalEvent.WITHDRAWAL_EVENT;
}
